export const EMOJI_CATEGORIES = [
  { id: 'smileys', label: 'Smileys & Emotion', icon: '😀' },
  { id: 'people', label: 'People & Body', icon: '👋' },
  { id: 'animals', label: 'Animals & Nature', icon: '🐶' },
  { id: 'food', label: 'Food & Drink', icon: '🍕' },
  { id: 'travel', label: 'Travel & Places', icon: '🚗' },
  { id: 'activities', label: 'Activities', icon: '⚽' },
  { id: 'objects', label: 'Objects', icon: '💡' },
  { id: 'symbols', label: 'Symbols', icon: '❤️' }
];

export const EMOJI_DATA = [
  // --- SMILEYS & EMOTION ---
  { emoji: '😀', category: 'smileys', keywords: ['smile', 'happy', 'grin'] },
  { emoji: '😃', category: 'smileys', keywords: ['smile', 'happy', 'open mouth'] },
  { emoji: '😄', category: 'smileys', keywords: ['smile', 'happy', 'eyes closed'] },
  { emoji: '😁', category: 'smileys', keywords: ['smile', 'happy', 'beaming'] },
  { emoji: '😆', category: 'smileys', keywords: ['grin', 'laugh', 'squint'] },
  { emoji: '😅', category: 'smileys', keywords: ['sweat', 'laugh', 'nervous'] },
  { emoji: '🤣', category: 'smileys', keywords: ['rofl', 'laughing', 'rolling'] },
  { emoji: '😂', category: 'smileys', keywords: ['joy', 'laugh', 'tears'] },
  { emoji: '🙂', category: 'smileys', keywords: ['smile', 'slight'] },
  { emoji: '🙃', category: 'smileys', keywords: ['upside down', 'flipped'] },
  { emoji: '🫠', category: 'smileys', keywords: ['melting', 'hot', 'shame'] },
  { emoji: '😉', category: 'smileys', keywords: ['wink', 'flirty'] },
  { emoji: '😊', category: 'smileys', keywords: ['blush', 'happy', 'soft'] },
  { emoji: '😇', category: 'smileys', keywords: ['angel', 'halo', 'innocent'] },
  { emoji: '🥰', category: 'smileys', keywords: ['hearts', 'love', 'blush'] },
  { emoji: '😍', category: 'smileys', keywords: ['love', 'heart eyes'] },
  { emoji: '🤩', category: 'smileys', keywords: ['starstruck', 'wow'] },
  { emoji: '😘', category: 'smileys', keywords: ['kissing', 'heart', 'smooth'] },
  { emoji: '😗', category: 'smileys', keywords: ['kissing'] },
  { emoji: '☺️', category: 'smileys', keywords: ['smile', 'blush', 'sweet'] },
  { emoji: '😚', category: 'smileys', keywords: ['kissing', 'closed eyes'] },
  { emoji: '😙', category: 'smileys', keywords: ['kissing', 'smile'] },
  { emoji: '😋', category: 'smileys', keywords: ['yum', 'delicious', 'tongue'] },
  { emoji: '😛', category: 'smileys', keywords: ['tongue', 'playful'] },
  { emoji: '😜', category: 'smileys', keywords: ['wink', 'tongue', 'crazy'] },
  { emoji: '🤪', category: 'smileys', keywords: ['zany', 'crazy', 'goofy'] },
  { emoji: '😝', category: 'smileys', keywords: ['tongue', 'closed eyes', 'squint'] },
  { emoji: '🤑', category: 'smileys', keywords: ['money', 'rich', 'dollar'] },
  { emoji: '🤗', category: 'smileys', keywords: ['hugging', 'warmth', 'jazz hands'] },
  { emoji: '🫣', category: 'smileys', keywords: ['peeking', 'hiding', 'eye'] },
  { emoji: '🤭', category: 'smileys', keywords: ['giggle', 'hand over mouth', 'oops'] },
  { emoji: '🫢', category: 'smileys', keywords: ['open mouth', 'amazed', 'shock'] },
  { emoji: '🤫', category: 'smileys', keywords: ['shushing', 'quiet', 'secret'] },
  { emoji: '🫠', category: 'smileys', keywords: ['melting', 'hot', 'shame'] },
  { emoji: '🤔', category: 'smileys', keywords: ['thinking', 'curious', 'ponder'] },
  { emoji: '🫡', category: 'smileys', keywords: ['saluting', 'respect', 'yes sir'] },
  { emoji: '🤐', category: 'smileys', keywords: ['zipper', 'quiet', 'sealed'] },
  { emoji: '🤨', category: 'smileys', keywords: ['raised eyebrow', 'skeptical', 'suspicious'] },
  { emoji: '😐', category: 'smileys', keywords: ['neutral', 'poker face'] },
  { emoji: '😑', category: 'smileys', keywords: ['expressionless', 'meh', 'blank'] },
  { emoji: '😶', category: 'smileys', keywords: ['no mouth', 'silent'] },
  { emoji: '🫥', category: 'smileys', keywords: ['dotted line', 'invisible', 'disappearing'] },
  { emoji: '😶‍🌫️', category: 'smileys', keywords: ['face in clouds', 'absent-minded', 'fog'] },
  { emoji: '😏', category: 'smileys', keywords: ['smirk', 'cool', 'flirt'] },
  { emoji: '😒', category: 'smileys', keywords: ['unamused', 'side eye'] },
  { emoji: '🙄', category: 'smileys', keywords: ['rolling eyes', 'judging'] },
  { emoji: '😬', category: 'smileys', keywords: ['grimace', 'awkward', 'teeth'] },
  { emoji: '😮‍💨', category: 'smileys', keywords: ['face exhaling', 'relief', 'tired'] },
  { emoji: '🤥', category: 'smileys', keywords: ['lying', 'pinocchio', 'long nose'] },
  { emoji: '😌', category: 'smileys', keywords: ['relieved', 'peaceful'] },
  { emoji: '😔', category: 'smileys', keywords: ['pensive', 'sad', 'down'] },
  { emoji: '😪', category: 'smileys', keywords: ['sleepy', 'drool', 'tired'] },
  { emoji: '🤤', category: 'smileys', keywords: ['drooling', 'delicious'] },
  { emoji: '😴', category: 'smileys', keywords: ['sleeping', 'zzz'] },
  { emoji: '😷', category: 'smileys', keywords: ['mask', 'sick', 'doctor'] },
  { emoji: '🤒', category: 'smileys', keywords: ['thermometer', 'hot', 'febrile'] },
  { emoji: '🤕', category: 'smileys', keywords: ['bandage', 'hurt', 'head injury'] },
  { emoji: '🤢', category: 'smileys', keywords: ['nauseated', 'sick', 'green'] },
  { emoji: '🤮', category: 'smileys', keywords: ['vomiting', 'puking', 'gross'] },
  { emoji: '🤧', category: 'smileys', keywords: ['sneezing', 'allergy', 'tissue'] },
  { emoji: '🥵', category: 'smileys', keywords: ['hot', 'overheated', 'sun'] },
  { emoji: '🥶', category: 'smileys', keywords: ['cold', 'frozen', 'blue'] },
  { emoji: '🥴', category: 'smileys', keywords: ['woozy', 'drunk', 'dizzy'] },
  { emoji: '😵', category: 'smileys', keywords: ['dizzy', 'knocked out', 'dead'] },
  { emoji: '😵‍💫', category: 'smileys', keywords: ['face with spiral eyes', 'hypnotized', 'confused'] },
  { emoji: '🤯', category: 'smileys', keywords: ['exploding', 'mind blown', 'shock'] },
  { emoji: '🤠', category: 'smileys', keywords: ['cowboy', 'hat', 'wild west'] },
  { emoji: '🥳', category: 'smileys', keywords: ['partying', 'celebration', 'party'] },
  { emoji: '🥸', category: 'smileys', keywords: ['disguise', 'mustache', 'glasses'] },
  { emoji: '😎', category: 'smileys', keywords: ['cool', 'sunglasses'] },
  { emoji: '🤓', category: 'smileys', keywords: ['nerd', 'geek', 'glasses'] },
  { emoji: '🧐', category: 'smileys', keywords: ['monocle', 'inspect', 'curious'] },
  { emoji: '😕', category: 'smileys', keywords: ['confused', 'puzzled'] },
  { emoji: '🫤', category: 'smileys', keywords: ['diagonal mouth', 'skeptical', 'unsure'] },
  { emoji: '😟', category: 'smileys', keywords: ['worried', 'nervous'] },
  { emoji: '🙁', category: 'smileys', keywords: ['frown', 'sad'] },
  { emoji: '☹️', category: 'smileys', keywords: ['frown', 'unhappy'] },
  { emoji: '😮', category: 'smileys', keywords: ['shock', 'surprised', 'open mouth'] },
  { emoji: '😯', category: 'smileys', keywords: ['hushed', 'quiet shock'] },
  { emoji: '😲', category: 'smileys', keywords: ['astonished', 'amazed'] },
  { emoji: '😳', category: 'smileys', keywords: ['flushed', 'blush', 'surprised'] },
  { emoji: '🥺', category: 'smileys', keywords: ['pleading', 'pouty', 'sad'] },
  { emoji: '🥹', category: 'smileys', keywords: ['face holding back tears', 'moved', 'emotional'] },
  { emoji: '😦', category: 'smileys', keywords: ['frowning with open mouth', 'shock'] },
  { emoji: '😧', category: 'smileys', keywords: ['anguished', 'scared', 'pain'] },
  { emoji: '😨', category: 'smileys', keywords: ['fearful', 'scared', 'panic'] },
  { emoji: '😰', category: 'smileys', keywords: ['anxious with sweat', 'blue', 'panic'] },
  { emoji: '😥', category: 'smileys', keywords: ['sad but relieved', 'blue', 'tears'] },
  { emoji: '😢', category: 'smileys', keywords: ['crying', 'sad', 'tears'] },
  { emoji: '😭', category: 'smileys', keywords: ['sobbing', 'sad', 'tears', 'crying'] },
  { emoji: '😱', category: 'smileys', keywords: ['scream', 'fear', 'shock'] },
  { emoji: '😖', category: 'smileys', keywords: ['confounded', 'strained'] },
  { emoji: '😣', category: 'smileys', keywords: ['persevering', 'strained', 'closed eyes'] },
  { emoji: '😞', category: 'smileys', keywords: ['disappointed', 'sad'] },
  { emoji: '😓', category: 'smileys', keywords: ['downcast with sweat', 'sad', 'work'] },
  { emoji: '😩', category: 'smileys', keywords: ['weary', 'tired', 'moan'] },
  { emoji: '😫', category: 'smileys', keywords: ['tired', 'exhausted'] },
  { emoji: '🥱', category: 'smileys', keywords: ['yawning', 'tired', 'bored'] },
  { emoji: '😤', category: 'smileys', keywords: ['triumph', 'angry', 'steam'] },
  { emoji: '😡', category: 'smileys', keywords: ['pouting', 'angry', 'red'] },
  { emoji: '😠', category: 'smileys', keywords: ['angry', 'mad'] },
  { emoji: '🤬', category: 'smileys', keywords: ['cursing', 'censored', 'mad'] },
  { emoji: '😈', category: 'smileys', keywords: ['smiling face with horns', 'demon', 'devil'] },
  { emoji: '👿', category: 'smileys', keywords: ['pouting face with horns', 'demon', 'angry devil'] },
  { emoji: '💀', category: 'smileys', keywords: ['skull', 'dead', 'laughing'] },
  { emoji: '☠️', category: 'smileys', keywords: ['skull and crossbones', 'danger', 'poison'] },
  { emoji: '💩', category: 'smileys', keywords: ['poop', 'crap', 'shit'] },
  { emoji: '🤡', category: 'smileys', keywords: ['clown', 'silly', 'creepy'] },
  { emoji: '👹', category: 'smileys', keywords: ['ogre', 'monster', 'scary'] },
  { emoji: '👺', category: 'smileys', keywords: ['goblin', 'mask', 'evil'] },
  { emoji: '👻', category: 'smileys', keywords: ['ghost', 'scary', 'spooky'] },
  { emoji: '👽', category: 'smileys', keywords: ['alien', 'ufo', 'space'] },
  { emoji: '👾', category: 'smileys', keywords: ['invader', 'pixel alien', 'game'] },
  { emoji: '🤖', category: 'smileys', keywords: ['robot', 'bot', 'tech'] },
  { emoji: '😺', category: 'smileys', keywords: ['grinning cat'] },
  { emoji: '😸', category: 'smileys', keywords: ['grinning cat with smiling eyes'] },
  { emoji: '😹', category: 'smileys', keywords: ['cat with tears of joy'] },
  { emoji: '😻', category: 'smileys', keywords: ['smiling cat with heart-eyes'] },
  { emoji: '😼', category: 'smileys', keywords: ['cat with wry smile'] },
  { emoji: '😽', category: 'smileys', keywords: ['kissing cat'] },
  { emoji: '🙀', category: 'smileys', keywords: ['weary cat', 'shock'] },
  { emoji: '😿', category: 'smileys', keywords: ['crying cat'] },
  { emoji: '😾', category: 'smileys', keywords: ['pouting cat', 'angry'] },
  { emoji: '🙈', category: 'smileys', keywords: ['see no evil', 'monkey', 'hiding'] },
  { emoji: '🙉', category: 'smileys', keywords: ['hear no evil', 'monkey', 'quiet'] },
  { emoji: '🙊', category: 'smileys', keywords: ['speak no evil', 'monkey', 'hush'] },
  { emoji: '💋', category: 'smileys', keywords: ['kiss', 'lipstick', 'lips'] },
  { emoji: '💌', category: 'smileys', keywords: ['love letter', 'mail', 'heart'] },
  { emoji: '💘', category: 'smileys', keywords: ['heart with arrow', 'cupid', 'love'] },
  { emoji: '💝', category: 'smileys', keywords: ['heart with ribbon', 'gift', 'box'] },
  { emoji: '💖', category: 'smileys', keywords: ['sparkling heart', 'glowing'] },
  { emoji: '💗', category: 'smileys', keywords: ['growing heart', 'pulse'] },
  { emoji: '💓', category: 'smileys', keywords: ['beating heart', 'pulse'] },
  { emoji: '💞', category: 'smileys', keywords: ['revolving hearts'] },
  { emoji: '💕', category: 'smileys', keywords: ['two hearts', 'love'] },
  { emoji: '💟', category: 'smileys', keywords: ['heart decoration'] },
  { emoji: '❣️', category: 'smileys', keywords: ['heart exclamation'] },
  { emoji: '💔', category: 'smileys', keywords: ['broken heart', 'sad'] },
  { emoji: '❤️‍🔥', category: 'smileys', keywords: ['heart on fire', 'passion'] },
  { emoji: '❤️‍🩹', category: 'smileys', keywords: ['mending heart', 'healing'] },
  { emoji: '❤️', category: 'smileys', keywords: ['red heart', 'love'] },
  { emoji: '🧡', category: 'smileys', keywords: ['orange heart'] },
  { emoji: '💛', category: 'smileys', keywords: ['yellow heart'] },
  { emoji: '💚', category: 'smileys', keywords: ['green heart'] },
  { emoji: '💙', category: 'smileys', keywords: ['blue heart'] },
  { emoji: '💜', category: 'smileys', keywords: ['purple heart'] },
  { emoji: '🤎', category: 'smileys', keywords: ['brown heart'] },
  { emoji: '🖤', category: 'smileys', keywords: ['black heart'] },
  { emoji: '🤍', category: 'smileys', keywords: ['white heart'] },
  { emoji: '💯', category: 'smileys', keywords: ['hundred', 'score', 'perfect'] },
  { emoji: '💢', category: 'smileys', keywords: ['anger symbol', 'mad', 'vein'] },
  { emoji: '💥', category: 'smileys', keywords: ['boom', 'collision', 'bang'] },
  { emoji: '💫', category: 'smileys', keywords: ['dizzy', 'stars'] },
  { emoji: '💦', category: 'smileys', keywords: ['sweat droplets', 'water', 'hot'] },
  { emoji: '💨', category: 'smileys', keywords: ['dash', 'fast', 'running', 'wind'] },
  { emoji: '🕳️', category: 'smileys', keywords: ['hole', 'void'] },
  { emoji: '💣', category: 'smileys', keywords: ['bomb', 'danger', 'boom'] },
  { emoji: '💬', category: 'smileys', keywords: ['speech balloon', 'chat', 'talk'] },
  { emoji: '👁️‍🗨️', category: 'smileys', keywords: ['eye in speech bubble'] },
  { emoji: '🗨️', category: 'smileys', keywords: ['left speech bubble'] },
  { emoji: '🗯️', category: 'smileys', keywords: ['right anger bubble'] },
  { emoji: '💭', category: 'smileys', keywords: ['thought balloon', 'thinking'] },
  { emoji: '💤', category: 'smileys', keywords: ['zzz', 'sleeping', 'tired'] },

  // --- PEOPLE & BODY ---
  { emoji: '👋', category: 'people', keywords: ['wave', 'hello', 'bye'] },
  { emoji: '🤚', category: 'people', keywords: ['raised back of hand'] },
  { emoji: '🖐️', category: 'people', keywords: ['hand with fingers splayed', 'five'] },
  { emoji: '✋', category: 'people', keywords: ['raised hand', 'stop', 'high five'] },
  { emoji: '🖖', category: 'people', keywords: ['vulcan salute', 'star trek'] },
  { emoji: '🫱', category: 'people', keywords: ['rightward hand'] },
  { emoji: '🫲', category: 'people', keywords: ['leftward hand'] },
  { emoji: '🫵', category: 'people', keywords: ['index pointing at viewer', 'you'] },
  { emoji: '👌', category: 'people', keywords: ['ok', 'perfect'] },
  { emoji: '🤌', category: 'people', keywords: ['pinched fingers', 'italian', 'what'] },
  { emoji: '🤏', category: 'people', keywords: ['pinching hand', 'little bit'] },
  { emoji: '✌️', category: 'people', keywords: ['victory', 'peace'] },
  { emoji: '🤞', category: 'people', keywords: ['fingers crossed', 'luck'] },
  { emoji: '🫰', category: 'people', keywords: ['hand with index finger and thumb crossed', 'finger heart', 'money'] },
  { emoji: '🤟', category: 'people', keywords: ['love you gesture', 'ily'] },
  { emoji: '🤘', category: 'people', keywords: ['rock on', 'horns'] },
  { emoji: '🤙', category: 'people', keywords: ['call me', 'shaka'] },
  { emoji: '👈', category: 'people', keywords: ['point left'] },
  { emoji: '👉', category: 'people', keywords: ['point right'] },
  { emoji: '👆', category: 'people', keywords: ['point up'] },
  { emoji: '🖕', category: 'people', keywords: ['middle finger', 'rude'] },
  { emoji: '👇', category: 'people', keywords: ['point down'] },
  { emoji: '☝️', category: 'people', keywords: ['index up'] },
  { emoji: '🫵', category: 'people', keywords: ['pointing you'] },
  { emoji: '👍', category: 'people', keywords: ['thumbs up', 'yes', 'ok'] },
  { emoji: '👎', category: 'people', keywords: ['thumbs down', 'no'] },
  { emoji: '✊', category: 'people', keywords: ['raised fist', 'power'] },
  { emoji: '👊', category: 'people', keywords: ['oncoming fist', 'bro fist', 'punch'] },
  { emoji: '🤛', category: 'people', keywords: ['left-facing fist'] },
  { emoji: '🤜', category: 'people', keywords: ['right-facing fist'] },
  { emoji: '👏', category: 'people', keywords: ['clapping', 'bravo'] },
  { emoji: '🙌', category: 'people', keywords: ['raising hands', 'celebrate'] },
  { emoji: '🫶', category: 'people', keywords: ['heart hands', 'love'] },
  { emoji: '👐', category: 'people', keywords: ['open hands'] },
  { emoji: '🤲', category: 'people', keywords: ['palms up together', 'prayer', 'give'] },
  { emoji: '🤝', category: 'people', keywords: ['handshake', 'deal', 'agreement'] },
  { emoji: '🙏', category: 'people', keywords: ['folded hands', 'please', 'thank you', 'pray'] },
  { emoji: '✍️', category: 'people', keywords: ['writing', 'draw'] },
  { emoji: '💅', category: 'people', keywords: ['nail polish', 'fancy', 'slay'] },
  { emoji: '🤳', category: 'people', keywords: ['selfie'] },
  { emoji: '💪', category: 'people', keywords: ['muscle', 'strong', 'flex'] },
  { emoji: '🦾', category: 'people', keywords: ['mechanical arm', 'robot'] },
  { emoji: '🦿', category: 'people', keywords: ['mechanical leg', 'robot'] },
  { emoji: '🦵', category: 'people', keywords: ['leg'] },
  { emoji: '🦶', category: 'people', keywords: ['foot'] },
  { emoji: '👂', category: 'people', keywords: ['ear', 'listen'] },
  { emoji: '🦻', category: 'people', keywords: ['ear with hearing aid'] },
  { emoji: '👃', category: 'people', keywords: ['nose', 'smell'] },
  { emoji: '🧠', category: 'people', keywords: ['brain', 'smart', 'thinking'] },
  { emoji: '🫀', category: 'people', keywords: ['anatomical heart', 'medical'] },
  { emoji: '🫁', category: 'people', keywords: ['lungs', 'breath'] },
  { emoji: '🦷', category: 'people', keywords: ['tooth', 'dentist'] },
  { emoji: '🦴', category: 'people', keywords: ['bone', 'skeleton'] },
  { emoji: '👀', category: 'people', keywords: ['eyes', 'looking', 'sus'] },
  { emoji: '👁️', category: 'people', keywords: ['eye'] },
  { emoji: '👅', category: 'people', keywords: ['tongue'] },
  { emoji: '👄', category: 'people', keywords: ['mouth', 'lips'] },
  { emoji: '🫦', category: 'people', keywords: ['biting lip', 'flirty', 'nervous'] },
  { emoji: '👶', category: 'people', keywords: ['baby', 'boy', 'girl'] },
  { emoji: '🧒', category: 'people', keywords: ['child', 'kid'] },
  { emoji: '👦', category: 'people', keywords: ['boy', 'kid'] },
  { emoji: '👧', category: 'people', keywords: ['girl', 'kid'] },
  { emoji: '👤', category: 'people', keywords: ['silhouette', 'user', 'shadow'] },
  { emoji: '👥', category: 'people', keywords: ['silhouettes', 'users', 'group'] },
  { emoji: '🫂', category: 'people', keywords: ['people hugging', 'comfort'] },

  // --- ANIMALS & NATURE ---
  { emoji: '🐶', category: 'animals', keywords: ['dog', 'puppy', 'pet'] },
  { emoji: '🐱', category: 'animals', keywords: ['cat', 'kitten', 'pet'] },
  { emoji: '🐭', category: 'animals', keywords: ['mouse', 'rodent'] },
  { emoji: '🐹', category: 'animals', keywords: ['hamster', 'pet'] },
  { emoji: '🐰', category: 'animals', keywords: ['rabbit', 'bunny'] },
  { emoji: '🦊', category: 'animals', keywords: ['fox'] },
  { emoji: '🐻', category: 'animals', keywords: ['bear'] },
  { emoji: '🐼', category: 'animals', keywords: ['panda'] },
  { emoji: '🐻‍❄️', category: 'animals', keywords: ['polar bear'] },
  { emoji: '🐨', category: 'animals', keywords: ['koala'] },
  { emoji: '🐯', category: 'animals', keywords: ['tiger'] },
  { emoji: '🦁', category: 'animals', keywords: ['lion', 'king'] },
  { emoji: '🐮', category: 'animals', keywords: ['cow'] },
  { emoji: '🐷', category: 'animals', keywords: ['pig'] },
  { emoji: '🐽', category: 'animals', keywords: ['pig nose'] },
  { emoji: '🐸', category: 'animals', keywords: ['frog'] },
  { emoji: '🐵', category: 'animals', keywords: ['monkey', 'face'] },
  { emoji: '🙈', category: 'animals', keywords: ['see no evil monkey'] },
  { emoji: '🙉', category: 'animals', keywords: ['hear no evil monkey'] },
  { emoji: '🙊', category: 'animals', keywords: ['speak no evil monkey'] },
  { emoji: '🐒', category: 'animals', keywords: ['monkey'] },
  { emoji: '🐔', category: 'animals', keywords: ['chicken', 'hen'] },
  { emoji: '🐧', category: 'animals', keywords: ['penguin'] },
  { emoji: '🐦', category: 'animals', keywords: ['bird'] },
  { emoji: '🐤', category: 'animals', keywords: ['baby chick'] },
  { emoji: '🐣', category: 'animals', keywords: ['hatching chick'] },
  { emoji: '🐥', category: 'animals', keywords: ['chick'] },
  { emoji: '🦆', category: 'animals', keywords: ['duck'] },
  { emoji: '🦅', category: 'animals', keywords: ['eagle'] },
  { emoji: '🦉', category: 'animals', keywords: ['owl'] },
  { emoji: '🦇', category: 'animals', keywords: ['bat', 'vampire'] },
  { emoji: '🐺', category: 'animals', keywords: ['wolf'] },
  { emoji: '🐗', category: 'animals', keywords: ['boar'] },
  { emoji: '🐴', category: 'animals', keywords: ['horse'] },
  { emoji: '🦄', category: 'animals', keywords: ['unicorn', 'magic'] },
  { emoji: '🐝', category: 'animals', keywords: ['bee', 'insect'] },
  { emoji: '🪱', category: 'animals', keywords: ['worm'] },
  { emoji: '🐛', category: 'animals', keywords: ['bug', 'caterpillar'] },
  { emoji: '🦋', category: 'animals', keywords: ['butterfly'] },
  { emoji: '🐌', category: 'animals', keywords: ['snail'] },
  { emoji: '🐞', category: 'animals', keywords: ['lady beetle', 'luck'] },
  { emoji: '🐜', category: 'animals', keywords: ['ant'] },
  { emoji: '🦗', category: 'animals', keywords: ['cricket'] },
  { emoji: '🪳', category: 'animals', keywords: ['cockroach'] },
  { emoji: '🕷️', category: 'animals', keywords: ['spider', 'scary'] },
  { emoji: '🕸️', category: 'animals', keywords: ['web', 'spider'] },
  { emoji: '🦂', category: 'animals', keywords: ['scorpion', 'scorpio'] },
  { emoji: '🦟', category: 'animals', keywords: ['mosquito'] },
  { emoji: '🪰', category: 'animals', keywords: ['fly'] },
  { emoji: '🐢', category: 'animals', keywords: ['turtle'] },
  { emoji: '🐍', category: 'animals', keywords: ['snake'] },
  { emoji: '🦎', category: 'animals', keywords: ['lizard'] },
  { emoji: '🦖', category: 'animals', keywords: ['t-rex', 'dinosaur'] },
  { emoji: '🦕', category: 'animals', keywords: ['sauropod', 'dinosaur'] },
  { emoji: '🐙', category: 'animals', keywords: ['octopus'] },
  { emoji: '🦑', category: 'animals', keywords: ['squid'] },
  { emoji: '🦐', category: 'animals', keywords: ['shrimp'] },
  { emoji: '🦞', category: 'animals', keywords: ['lobster'] },
  { emoji: '🦀', category: 'animals', keywords: ['crab'] },
  { emoji: '🐡', category: 'animals', keywords: ['blowfish'] },
  { emoji: '🐠', category: 'animals', keywords: ['tropical fish'] },
  { emoji: '🐟', category: 'animals', keywords: ['fish'] },
  { emoji: '🐬', category: 'animals', keywords: ['dolphin'] },
  { emoji: '🐳', category: 'animals', keywords: ['whale', 'spouting'] },
  { emoji: '🐋', category: 'animals', keywords: ['whale'] },
  { emoji: '🦈', category: 'animals', keywords: ['shark'] },
  { emoji: '🐊', category: 'animals', keywords: ['crocodile'] },
  { emoji: '🐅', category: 'animals', keywords: ['tiger'] },
  { emoji: '🐆', category: 'animals', keywords: ['leopard'] },
  { emoji: '🦓', category: 'animals', keywords: ['zebra'] },
  { emoji: '🦍', category: 'animals', keywords: ['gorilla'] },
  { emoji: '🦧', category: 'animals', keywords: ['orangutan'] },
  { emoji: '🐘', category: 'animals', keywords: ['elephant'] },
  { emoji: '🦛', category: 'animals', keywords: ['hippo'] },
  { emoji: '🦏', category: 'animals', keywords: ['rhino'] },
  { emoji: '🐪', category: 'animals', keywords: ['camel'] },
  { emoji: '🦒', category: 'animals', keywords: ['giraffe'] },
  { emoji: '🦘', category: 'animals', keywords: ['kangaroo'] },
  { emoji: '🦬', category: 'animals', keywords: ['bison'] },
  { emoji: '🐃', category: 'animals', keywords: ['water buffalo'] },
  { emoji: '🐂', category: 'animals', keywords: ['ox'] },
  { emoji: '🐄', category: 'animals', keywords: ['cow'] },
  { emoji: '🐏', category: 'animals', keywords: ['ram'] },
  { emoji: '🐑', category: 'animals', keywords: ['sheep', 'ewe'] },
  { emoji: '🐐', category: 'animals', keywords: ['goat'] },
  { emoji: '🦌', category: 'animals', keywords: ['deer'] },
  { emoji: '🦙', category: 'animals', keywords: ['llama'] },
  { emoji: '🦥', category: 'animals', keywords: ['sloth'] },
  { emoji: '🦨', category: 'animals', keywords: ['skunk'] },
  { emoji: '🦡', category: 'animals', keywords: ['badger'] },
  { emoji: '🦃', category: 'animals', keywords: ['turkey', 'thanksgiving'] },
  { emoji: '🕊️', category: 'animals', keywords: ['dove', 'peace'] },
  { emoji: '🐕', category: 'animals', keywords: ['dog'] },
  { emoji: '🐩', category: 'animals', keywords: ['poodle'] },
  { emoji: '🦮', category: 'animals', keywords: ['guide dog'] },
  { emoji: '🐾', category: 'animals', keywords: ['paw prints'] },
  { emoji: '🐉', category: 'animals', keywords: ['dragon'] },
  { emoji: '🐲', category: 'animals', keywords: ['dragon face'] },
  { emoji: '🌵', category: 'animals', keywords: ['cactus', 'desert'] },
  { emoji: '🎄', category: 'animals', keywords: ['christmas tree'] },
  { emoji: '🌲', category: 'animals', keywords: ['evergreen tree'] },
  { emoji: '🌳', category: 'animals', keywords: ['deciduous tree'] },
  { emoji: '🌴', category: 'animals', keywords: ['palm tree', 'beach'] },
  { emoji: '🌱', category: 'animals', keywords: ['seedling', 'plant', 'grow'] },
  { emoji: '🌿', category: 'animals', keywords: ['herb'] },
  { emoji: '☘️', category: 'animals', keywords: ['shamrock', 'luck'] },
  { emoji: '🍀', category: 'animals', keywords: ['four leaf clover', 'luck'] },
  { emoji: '🎍', category: 'animals', keywords: ['pine decoration'] },
  { emoji: '🎋', category: 'animals', keywords: ['tanabata tree'] },
  { emoji: '🍃', category: 'animals', keywords: ['leaf fluttering in wind'] },
  { emoji: '🍂', category: 'animals', keywords: ['fallen leaf', 'autumn'] },
  { emoji: '🍁', category: 'animals', keywords: ['maple leaf', 'canada'] },
  { emoji: '🍄', category: 'animals', keywords: ['mushroom'] },
  { emoji: '🌾', category: 'animals', keywords: ['sheaf of rice'] },
  { emoji: '💐', category: 'animals', keywords: ['bouquet', 'flowers'] },
  { emoji: '🌷', category: 'animals', keywords: ['tulip'] },
  { emoji: '🌹', category: 'animals', keywords: ['rose', 'love'] },
  { emoji: '🥀', category: 'animals', keywords: ['wilted flower', 'sad'] },
  { emoji: '🌺', category: 'animals', keywords: ['hibiscus'] },
  { emoji: '🌸', category: 'animals', keywords: ['cherry blossom', 'sakura'] },
  { emoji: '🌼', category: 'animals', keywords: ['blossom'] },
  { emoji: '🌻', category: 'animals', keywords: ['sunflower'] },
  { emoji: '🌞', category: 'animals', keywords: ['sun with face'] },
  { emoji: '🌝', category: 'animals', keywords: ['full moon with face'] },
  { emoji: '🌚', category: 'animals', keywords: ['new moon with face'] },
  { emoji: '🌛', category: 'animals', keywords: ['first quarter moon with face'] },
  { emoji: '🌜', category: 'animals', keywords: ['last quarter moon with face'] },
  { emoji: '🌙', category: 'animals', keywords: ['crescent moon', 'night'] },
  { emoji: '🌍', category: 'animals', keywords: ['earth globe europe-africa'] },
  { emoji: '🌎', category: 'animals', keywords: ['earth globe americas'] },
  { emoji: '🌏', category: 'animals', keywords: ['earth globe asia-australia'] },
  { emoji: '🌐', category: 'animals', keywords: ['globe with meridians', 'internet'] },
  { emoji: '🌋', category: 'animals', keywords: ['volcano', 'hot'] },
  { emoji: '🌌', category: 'animals', keywords: ['milky way', 'space'] },
  { emoji: '🌠', category: 'animals', keywords: ['shooting star'] },
  { emoji: '⭐', category: 'animals', keywords: ['star'] },
  { emoji: '☀️', category: 'animals', keywords: ['sun', 'hot'] },
  { emoji: '⛅', category: 'animals', keywords: ['sun behind cloud'] },
  { emoji: '☁️', category: 'animals', keywords: ['cloud'] },
  { emoji: '⚡', category: 'animals', keywords: ['high voltage', 'lightning', 'zap'] },
  { emoji: '🔥', category: 'animals', keywords: ['fire', 'hot', 'lit'] },
  { emoji: '💥', category: 'animals', keywords: ['collision', 'boom'] },
  { emoji: '❄️', category: 'animals', keywords: ['snowflake', 'cold'] },
  { emoji: '🌨️', category: 'animals', keywords: ['cloud with snow'] },
  { emoji: '⛈️', category: 'animals', keywords: ['cloud with lightning and rain'] },
  { emoji: '🌧️', category: 'animals', keywords: ['cloud with rain'] },
  { emoji: '💧', category: 'animals', keywords: ['droplet', 'water'] },
  { emoji: '💦', category: 'animals', keywords: ['sweat drops', 'water'] },
  { emoji: '🌊', category: 'animals', keywords: ['water wave', 'ocean'] },
  { emoji: '🌈', category: 'animals', keywords: ['rainbow', 'proud'] },

  // --- FOOD & DRINK ---
  { emoji: '🍇', category: 'food', keywords: ['grapes', 'fruit'] },
  { emoji: '🍈', category: 'food', keywords: ['melon', 'fruit'] },
  { emoji: '🍉', category: 'food', keywords: ['watermelon', 'fruit'] },
  { emoji: '🍊', category: 'food', keywords: ['tangerine', 'orange', 'fruit'] },
  { emoji: '🍋', category: 'food', keywords: ['lemon', 'citrus'] },
  { emoji: '🍋‍🟩', category: 'food', keywords: ['lime', 'citrus'] },
  { emoji: '🍌', category: 'food', keywords: ['banana', 'fruit'] },
  { emoji: '🍍', category: 'food', keywords: ['pineapple', 'fruit'] },
  { emoji: '🥭', category: 'food', keywords: ['mango', 'fruit'] },
  { emoji: '🍎', category: 'food', keywords: ['red apple', 'fruit'] },
  { emoji: '🍏', category: 'food', keywords: ['green apple', 'fruit'] },
  { emoji: '🍐', category: 'food', keywords: ['pear', 'fruit'] },
  { emoji: '🍑', category: 'food', keywords: ['peach', 'fruit', 'butt'] },
  { emoji: '🍒', category: 'food', keywords: ['cherries', 'fruit'] },
  { emoji: '🍓', category: 'food', keywords: ['strawberry', 'fruit'] },
  { emoji: '🫐', category: 'food', keywords: ['blueberries', 'fruit'] },
  { emoji: '🥝', category: 'food', keywords: ['kiwi fruit'] },
  { emoji: '🍅', category: 'food', keywords: ['tomato', 'vegetable'] },
  { emoji: '🫒', category: 'food', keywords: ['olive'] },
  { emoji: '🥥', category: 'food', keywords: ['coconut'] },
  { emoji: '🥑', category: 'food', keywords: ['avocado', 'healthy'] },
  { emoji: '🍆', category: 'food', keywords: ['eggplant', 'vegetable', 'penis'] },
  { emoji: '🥔', category: 'food', keywords: ['potato', 'starch'] },
  { emoji: '🥕', category: 'food', keywords: ['carrot', 'vegetable'] },
  { emoji: '🌽', category: 'food', keywords: ['ear of corn', 'maize'] },
  { emoji: '🌶️', category: 'food', keywords: ['hot pepper', 'spicy'] },
  { emoji: '🫑', category: 'food', keywords: ['bell pepper'] },
  { emoji: '🥒', category: 'food', keywords: ['cucumber'] },
  { emoji: '🥬', category: 'food', keywords: ['leafy green', 'salad'] },
  { emoji: '🥦', category: 'food', keywords: ['broccoli'] },
  { emoji: '🧄', category: 'food', keywords: ['garlic'] },
  { emoji: '🧅', category: 'food', keywords: ['onion'] },
  { emoji: '🍄', category: 'food', keywords: ['mushroom'] },
  { emoji: '🫟', category: 'food', keywords: ['ginger root'] },
  { emoji: '🥜', category: 'food', keywords: ['peanuts', 'nut'] },
  { emoji: '🫘', category: 'food', keywords: ['beans'] },
  { emoji: '🌰', category: 'food', keywords: ['chestnut'] },
  { emoji: '🫗', category: 'food', keywords: ['pouring liquid'] },
  { emoji: '🍞', category: 'food', keywords: ['bread', 'toast'] },
  { emoji: '🥐', category: 'food', keywords: ['croissant'] },
  { emoji: '🥖', category: 'food', keywords: ['baguette bread'] },
  { emoji: '🫓', category: 'food', keywords: ['flatbread'] },
  { emoji: '🥨', category: 'food', keywords: ['pretzel'] },
  { emoji: '🥯', category: 'food', keywords: ['bagel'] },
  { emoji: '🥞', category: 'food', keywords: ['pancakes', 'breakfast'] },
  { emoji: '🧇', category: 'food', keywords: ['waffle'] },
  { emoji: '🧀', category: 'food', keywords: ['cheese wedge'] },
  { emoji: '🍖', category: 'food', keywords: ['meat on bone'] },
  { emoji: '🍗', category: 'food', keywords: ['poultry leg', 'chicken'] },
  { emoji: '🥩', category: 'food', keywords: ['cut of meat', 'steak'] },
  { emoji: '🥓', category: 'food', keywords: ['bacon'] },
  { emoji: '🍔', category: 'food', keywords: ['hamburger', 'burger', 'fast food'] },
  { emoji: '🍟', category: 'food', keywords: ['french fries', 'fast food'] },
  { emoji: '🍕', category: 'food', keywords: ['pizza', 'fast food'] },
  { emoji: '🌭', category: 'food', keywords: ['hot dog'] },
  { emoji: '🥪', category: 'food', keywords: ['sandwich'] },
  { emoji: '🌮', category: 'food', keywords: ['taco', 'mexican'] },
  { emoji: '🌯', category: 'food', keywords: ['burrito', 'mexican'] },
  { emoji: '🫔', category: 'food', keywords: ['tamale'] },
  { emoji: '🥙', category: 'food', keywords: ['stuffed flatbread', 'gyro'] },
  { emoji: '🧆', category: 'food', keywords: ['falafel'] },
  { emoji: '🥚', category: 'food', keywords: ['egg'] },
  { emoji: '🍳', category: 'food', keywords: ['cooking', 'egg', 'frying pan'] },
  { emoji: '🥘', category: 'food', keywords: ['shallow pan of food', 'paella'] },
  { emoji: '🍲', category: 'food', keywords: ['pot of food', 'stew'] },
  { emoji: '🫕', category: 'food', keywords: ['fondue'] },
  { emoji: '🥣', category: 'food', keywords: ['bowl with spoon', 'cereal', 'soup'] },
  { emoji: '🥗', category: 'food', keywords: ['green salad', 'healthy'] },
  { emoji: '🍿', category: 'food', keywords: ['popcorn', 'movie'] },
  { emoji: '🧈', category: 'food', keywords: ['butter'] },
  { emoji: '🧂', category: 'food', keywords: ['salt'] },
  { emoji: '🥫', category: 'food', keywords: ['canned food'] },
  { emoji: '🍱', category: 'food', keywords: ['bento box'] },
  { emoji: '🍘', category: 'food', keywords: ['rice cracker'] },
  { emoji: '🍙', category: 'food', keywords: ['rice ball'] },
  { emoji: '🍚', category: 'food', keywords: ['cooked rice'] },
  { emoji: '🍛', category: 'food', keywords: ['curry rice'] },
  { emoji: '🍜', category: 'food', keywords: ['steaming bowl', 'ramen', 'noodles'] },
  { emoji: '🍝', category: 'food', keywords: ['spaghetti', 'pasta'] },
  { emoji: '🍠', category: 'food', keywords: ['roasted sweet potato'] },
  { emoji: '🍢', category: 'food', keywords: ['oden'] },
  { emoji: '🍣', category: 'food', keywords: ['sushi'] },
  { emoji: '🍤', category: 'food', keywords: ['fried shrimp', 'tempura'] },
  { emoji: '🍥', category: 'food', keywords: ['fish cake with swirl', 'naruto'] },
  { emoji: '🥮', category: 'food', keywords: ['moon cake'] },
  { emoji: '🍡', category: 'food', keywords: ['dango'] },
  { emoji: '🥟', category: 'food', keywords: ['dumpling'] },
  { emoji: '🥠', category: 'food', keywords: ['fortune cookie'] },
  { emoji: '🥡', category: 'food', keywords: ['takeout box', 'chinese food'] },
  { emoji: '🦀', category: 'food', keywords: ['crab'] },
  { emoji: '🦞', category: 'food', keywords: ['lobster'] },
  { emoji: '🦐', category: 'food', keywords: ['shrimp'] },
  { emoji: '🦑', category: 'food', keywords: ['squid'] },
  { emoji: '🦪', category: 'food', keywords: ['oyster'] },
  { emoji: '🍦', category: 'food', keywords: ['soft serve', 'ice cream'] },
  { emoji: '🍧', category: 'food', keywords: ['shaved ice'] },
  { emoji: '🍨', category: 'food', keywords: ['ice cream'] },
  { emoji: '🍩', category: 'food', keywords: ['doughnut', 'donut'] },
  { emoji: '🍪', category: 'food', keywords: ['cookie', 'biscuit'] },
  { emoji: '🎂', category: 'food', keywords: ['birthday cake'] },
  { emoji: '🍰', category: 'food', keywords: ['shortcake', 'cake slice'] },
  { emoji: '🧁', category: 'food', keywords: ['cupcake'] },
  { emoji: '🥧', category: 'food', keywords: ['pie'] },
  { emoji: '🍫', category: 'food', keywords: ['chocolate bar'] },
  { emoji: '🍬', category: 'food', keywords: ['candy'] },
  { emoji: '🍭', category: 'food', keywords: ['lollipop'] },
  { emoji: '🍮', category: 'food', keywords: ['custard', 'flan'] },
  { emoji: '🍯', category: 'food', keywords: ['honey pot'] },
  { emoji: '🍼', category: 'food', keywords: ['baby bottle', 'milk'] },
  { emoji: '🥛', category: 'food', keywords: ['glass of milk'] },
  { emoji: '☕', category: 'food', keywords: ['hot beverage', 'coffee', 'tea'] },
  { emoji: '🫖', category: 'food', keywords: ['teapot'] },
  { emoji: '🍵', category: 'food', keywords: ['teacup without handle', 'green tea'] },
  { emoji: '🍶', category: 'food', keywords: ['sake'] },
  { emoji: '🍾', category: 'food', keywords: ['bottle with popping cork', 'champagne', 'party'] },
  { emoji: '🍷', category: 'food', keywords: ['wine glass'] },
  { emoji: '🍸', category: 'food', keywords: ['cocktail glass', 'martini'] },
  { emoji: '🍹', category: 'food', keywords: ['tropical drink'] },
  { emoji: '🍺', category: 'food', keywords: ['beer mug'] },
  { emoji: '🍻', category: 'food', keywords: ['clinking beer mugs', 'cheers'] },
  { emoji: '🥂', category: 'food', keywords: ['clinking glasses', 'celebrate'] },
  { emoji: '🥃', category: 'food', keywords: ['tumbler glass', 'whiskey'] },
  { emoji: '🫗', category: 'food', keywords: ['pouring liquid'] },
  { emoji: '🥤', category: 'food', keywords: ['cup with straw', 'soda', 'shake'] },
  { emoji: '🧋', category: 'food', keywords: ['bubble tea', 'boba'] },
  { emoji: '🧃', category: 'food', keywords: ['beverage box', 'juice'] },
  { emoji: '🧉', category: 'food', keywords: ['mate'] },
  { emoji: '🧊', category: 'food', keywords: ['ice cube', 'cold'] },
  { emoji: '🥢', category: 'food', keywords: ['chopsticks'] },
  { emoji: '🍽️', category: 'food', keywords: ['fork and knife with plate', 'dinner'] },
  { emoji: '🍴', category: 'food', keywords: ['fork and knife'] },
  { emoji: '🥄', category: 'food', keywords: ['spoon'] },

  // --- TRAVEL & PLACES ---
  { emoji: '🚗', category: 'travel', keywords: ['automobile', 'car'] },
  { emoji: '🚕', category: 'travel', keywords: ['taxi', 'cab'] },
  { emoji: '🚙', category: 'travel', keywords: ['recreational vehicle', 'suv'] },
  { emoji: '🚌', category: 'travel', keywords: ['bus'] },
  { emoji: '🚎', category: 'travel', keywords: ['trolleybus'] },
  { emoji: '🏎️', category: 'travel', keywords: ['racing car', 'formula1'] },
  { emoji: '🚓', category: 'travel', keywords: ['police car'] },
  { emoji: '🚑', category: 'travel', keywords: ['ambulance'] },
  { emoji: '🚒', category: 'travel', keywords: ['fire engine'] },
  { emoji: '🚐', category: 'travel', keywords: ['minibus'] },
  { emoji: '🚚', category: 'travel', keywords: ['delivery truck'] },
  { emoji: '🚛', category: 'travel', keywords: ['articulated lorry', 'truck'] },
  { emoji: '🚜', category: 'travel', keywords: ['tractor'] },
  { emoji: '🚲', category: 'travel', keywords: ['bicycle', 'bike'] },
  { emoji: '🛴', category: 'travel', keywords: ['kick scooter'] },
  { emoji: '🛵', category: 'travel', keywords: ['motor scooter', 'vespa'] },
  { emoji: '🏍️', category: 'travel', keywords: ['motorcycle'] },
  { emoji: '🛺', category: 'travel', keywords: ['auto rickshaw'] },
  { emoji: '🚔', category: 'travel', keywords: ['oncoming police car'] },
  { emoji: '🚍', category: 'travel', keywords: ['oncoming bus'] },
  { emoji: '🚘', category: 'travel', keywords: ['oncoming automobile'] },
  { emoji: '🚖', category: 'travel', keywords: ['oncoming taxi'] },
  { emoji: '🚟', category: 'travel', keywords: ['aerial tramway'] },
  { emoji: '🚠', category: 'travel', keywords: ['mountain cableway'] },
  { emoji: '🚠', category: 'travel', keywords: ['monorail'] },
  { emoji: '🚄', category: 'travel', keywords: ['high-speed train'] },
  { emoji: '🚅', category: 'travel', keywords: ['bullet train'] },
  { emoji: '🚆', category: 'travel', keywords: ['train'] },
  { emoji: '🚇', category: 'travel', keywords: ['metro', 'subway'] },
  { emoji: '🚈', category: 'travel', keywords: ['light rail'] },
  { emoji: '🚉', category: 'travel', keywords: ['station'] },
  { emoji: '🚊', category: 'travel', keywords: ['tram'] },
  { emoji: '⛴️', category: 'travel', keywords: ['ferry', 'boat'] },
  { emoji: '🛳️', category: 'travel', keywords: ['passenger ship', 'cruise'] },
  { emoji: '🚢', category: 'travel', keywords: ['ship'] },
  { emoji: '✈️', category: 'travel', keywords: ['airplane', 'flight'] },
  { emoji: '🛩️', category: 'travel', keywords: ['small airplane'] },
  { emoji: '🚀', category: 'travel', keywords: ['rocket', 'space'] },
  { emoji: '🛰️', category: 'travel', keywords: ['satellite'] },
  { emoji: '🛸', category: 'travel', keywords: ['ufo', 'alien'] },
  { emoji: '🚁', category: 'travel', keywords: ['helicopter'] },
  { emoji: '🛶', category: 'travel', keywords: ['canoe'] },
  { emoji: '⛵', category: 'travel', keywords: ['sailboat', 'boat'] },
  { emoji: '🚤', category: 'travel', keywords: ['speedboat'] },
  { emoji: '⚓', category: 'travel', keywords: ['anchor', 'sea'] },
  { emoji: '🎡', category: 'travel', keywords: ['ferris wheel', 'fair'] },
  { emoji: '🎢', category: 'travel', keywords: ['roller coaster', 'fair'] },
  { emoji: '🎠', category: 'travel', keywords: ['carousel horse'] },
  { emoji: '🏗️', category: 'travel', keywords: ['building construction'] },
  { emoji: '🏠', category: 'travel', keywords: ['house'] },
  { emoji: '🏡', category: 'travel', keywords: ['house with garden'] },
  { emoji: '🏘️', category: 'travel', keywords: ['houses'] },
  { emoji: '🏚️', category: 'travel', keywords: ['derelict house', 'old'] },
  { emoji: '🏢', category: 'travel', keywords: ['office building'] },
  { emoji: '🏣', category: 'travel', keywords: ['japanese post office'] },
  { emoji: '🏤', category: 'travel', keywords: ['post office'] },
  { emoji: '🏥', category: 'travel', keywords: ['hospital'] },
  { emoji: '🏦', category: 'travel', keywords: ['bank'] },
  { emoji: '🏨', category: 'travel', keywords: ['hotel'] },
  { emoji: '🏩', category: 'travel', keywords: ['love hotel'] },
  { emoji: '🏪', category: 'travel', keywords: ['convenience store'] },
  { emoji: '🏫', category: 'travel', keywords: ['school'] },
  { emoji: '🏬', category: 'travel', keywords: ['department store'] },
  { emoji: '🏭', category: 'travel', keywords: ['factory'] },
  { emoji: '🏯', category: 'travel', keywords: ['japanese castle'] },
  { emoji: '🏰', category: 'travel', keywords: ['castle'] },
  { emoji: '💒', category: 'travel', keywords: ['wedding'] },
  { emoji: '🗼', category: 'travel', keywords: ['tokyo tower'] },
  { emoji: '🗽', category: 'travel', keywords: ['statue of liberty', 'usa'] },
  { emoji: '⛪', category: 'travel', keywords: ['church'] },
  { emoji: '🕌', category: 'travel', keywords: ['mosque'] },
  { emoji: '🛕', category: 'travel', keywords: ['hindu temple'] },
  { emoji: '✡️', category: 'travel', keywords: ['star of david'] },
  { emoji: '⛩️', category: 'travel', keywords: ['shinto shrine'] },
  { emoji: '🕋', category: 'travel', keywords: ['kaaba'] },
  { emoji: '⛲', category: 'travel', keywords: ['fountain'] },
  { emoji: '⛺', category: 'travel', keywords: ['tent', 'camping'] },
  { emoji: '🌁', category: 'travel', keywords: ['foggy'] },
  { emoji: '🌃', category: 'travel', keywords: ['night with stars'] },
  { emoji: '🏙️', category: 'travel', keywords: ['cityscape', 'buildings'] },
  { emoji: '🌄', category: 'travel', keywords: ['sunrise over mountains'] },
  { emoji: '🌅', category: 'travel', keywords: ['sunrise', 'beach'] },
  { emoji: '🌆', category: 'travel', keywords: ['cityscape at dusk'] },
  { emoji: '🌇', category: 'travel', keywords: ['sunset'] },
  { emoji: '🌉', category: 'travel', keywords: ['bridge at night'] },
  { emoji: '🎠', category: 'travel', keywords: ['carousel'] },
  { emoji: '🎡', category: 'travel', keywords: ['ferris wheel'] },
  { emoji: '🎢', category: 'travel', keywords: ['roller coaster'] },
  { emoji: '⛰️', category: 'travel', keywords: ['mountain'] },
  { emoji: '🏔️', category: 'travel', keywords: ['snow-capped mountain'] },
  { emoji: '🗻', category: 'travel', keywords: ['mount fuji'] },
  { emoji: '🌋', category: 'travel', keywords: ['volcano'] },
  { emoji: '🏗️', category: 'travel', keywords: ['construction'] },
  { emoji: '🧱', category: 'travel', keywords: ['brick'] },
  { emoji: '🪵', category: 'travel', keywords: ['wood'] },
  { emoji: '🛖', category: 'travel', keywords: ['hut'] },
  { emoji: '⛺', category: 'travel', keywords: ['camping'] },
  { emoji: '🏞️', category: 'travel', keywords: ['national park'] },
  { emoji: '🏟️', category: 'travel', keywords: ['stadium'] },
  { emoji: '🏜️', category: 'travel', keywords: ['desert'] },
  { emoji: '🏝️', category: 'travel', keywords: ['island'] },

  // --- ACTIVITIES ---
  { emoji: '⚽', category: 'activities', keywords: ['soccer', 'football', 'ball'] },
  { emoji: '🏀', category: 'activities', keywords: ['basketball', 'ball'] },
  { emoji: '🏈', category: 'activities', keywords: ['american football', 'ball'] },
  { emoji: '⚾', category: 'activities', keywords: ['baseball', 'ball'] },
  { emoji: '🥎', category: 'activities', keywords: ['softball', 'ball'] },
  { emoji: '🎾', category: 'activities', keywords: ['tennis', 'ball'] },
  { emoji: '🏐', category: 'activities', keywords: ['volleyball', 'ball'] },
  { emoji: '🏉', category: 'activities', keywords: ['rugby football', 'ball'] },
  { emoji: '🎱', category: 'activities', keywords: ['billiards', 'pool', 'eight ball'] },
  { emoji: '🏓', category: 'activities', keywords: ['ping pong', 'table tennis'] },
  { emoji: '🏸', category: 'activities', keywords: ['badminton'] },
  { emoji: '🏒', category: 'activities', keywords: ['ice hockey'] },
  { emoji: '🏑', category: 'activities', keywords: ['field hockey'] },
  { emoji: '🥍', category: 'activities', keywords: ['lacrosse'] },
  { emoji: '🏏', category: 'activities', keywords: ['cricket game'] },
  { emoji: '🪃', category: 'activities', keywords: ['boomerang'] },
  { emoji: '🥅', category: 'activities', keywords: ['goal net'] },
  { emoji: '⛳', category: 'activities', keywords: ['flag in hole', 'golf'] },
  { emoji: '🏹', category: 'activities', keywords: ['bow and arrow', 'archery'] },
  { emoji: '🎣', category: 'activities', keywords: ['fishing pole', 'fish'] },
  { emoji: '🤿', category: 'activities', keywords: ['diving mask', 'swim'] },
  { emoji: '🥊', category: 'activities', keywords: ['boxing glove'] },
  { emoji: '🥋', category: 'activities', keywords: ['martial arts uniform', 'karate'] },
  { emoji: '⛸️', category: 'activities', keywords: ['ice skate'] },
  { emoji: '🛷', category: 'activities', keywords: ['sled'] },
  { emoji: '🎿', category: 'activities', keywords: ['skis'] },
  { emoji: '🏂', category: 'activities', keywords: ['snowboarder'] },
  { emoji: '🏋️', category: 'activities', keywords: ['weight lifter', 'gym'] },
  { emoji: '🤺', category: 'activities', keywords: ['fencer'] },
  { emoji: '🤼', category: 'activities', keywords: ['wrestlers'] },
  { emoji: '🤸', category: 'activities', keywords: ['person cartwheeling', 'gymnast'] },
  { emoji: '⛹️', category: 'activities', keywords: ['person bouncing ball', 'basketball'] },
  { emoji: '🧘', category: 'activities', keywords: ['meditation', 'yoga'] },
  { emoji: '🏇', category: 'activities', keywords: ['horse racing'] },
  { emoji: '🏄', category: 'activities', keywords: ['surfer', 'beach'] },
  { emoji: '🏊', category: 'activities', keywords: ['swimmer', 'pool'] },
  { emoji: '🤽', category: 'activities', keywords: ['water polo'] },
  { emoji: '🚣', category: 'activities', keywords: ['rowboat'] },
  { emoji: '🧗', category: 'activities', keywords: ['climber', 'mountain'] },
  { emoji: '🚵', category: 'activities', keywords: ['mountain biker'] },
  { emoji: '🚴', category: 'activities', keywords: ['bicyclist'] },
  { emoji: '🏆', category: 'activities', keywords: ['trophy', 'winner'] },
  { emoji: '🥇', category: 'activities', keywords: ['1st place medal', 'gold'] },
  { emoji: '🥈', category: 'activities', keywords: ['2nd place medal', 'silver'] },
  { emoji: '🥉', category: 'activities', keywords: ['3rd place medal', 'bronze'] },
  { emoji: '🏅', category: 'activities', keywords: ['sports medal'] },
  { emoji: '🎖️', category: 'activities', keywords: ['military medal'] },
  { emoji: '🏵️', category: 'activities', keywords: ['rosette'] },
  { emoji: '🎫', category: 'activities', keywords: ['ticket'] },
  { emoji: '🎟️', category: 'activities', keywords: ['admission tickets'] },
  { emoji: '🎭', category: 'activities', keywords: ['performing arts', 'theater', 'mask'] },
  { emoji: '🎨', category: 'activities', keywords: ['artist palette', 'art', 'paint'] },
  { emoji: '🎬', category: 'activities', keywords: ['clapper board', 'movie'] },
  { emoji: '🎤', category: 'activities', keywords: ['microphone', 'sing'] },
  { emoji: '🎧', category: 'activities', keywords: ['headphone', 'music'] },
  { emoji: '🎼', category: 'activities', keywords: ['musical score'] },
  { emoji: '🎹', category: 'activities', keywords: ['musical keyboard', 'piano'] },
  { emoji: '🥁', category: 'activities', keywords: ['drum'] },
  { emoji: '🎷', category: 'activities', keywords: ['saxophone'] },
  { emoji: '🎺', category: 'activities', keywords: ['trumpet'] },
  { emoji: '🎸', category: 'activities', keywords: ['guitar'] },
  { emoji: '🪕', category: 'activities', keywords: ['banjo'] },
  { emoji: '🎻', category: 'activities', keywords: ['violin'] },
  { emoji: '🎮', category: 'activities', keywords: ['video game', 'controller'] },
  { emoji: '🕹️', category: 'activities', keywords: ['joystick'] },
  { emoji: '🎰', category: 'activities', keywords: ['slot machine', 'casino'] },
  { emoji: '🎲', category: 'activities', keywords: ['game die', 'dice', 'luck'] },
  { emoji: '♟️', category: 'activities', keywords: ['chess pawn'] },
  { emoji: '🧩', category: 'activities', keywords: ['puzzle piece'] },
  { emoji: '🧸', category: 'activities', keywords: ['teddy bear'] },
  { emoji: '🃏', category: 'activities', keywords: ['joker', 'cards'] },
  { emoji: '🀄', category: 'activities', keywords: ['mahjong red dragon'] },
  { emoji: '🎴', category: 'activities', keywords: ['flower playing cards'] },
  { emoji: '🎯', category: 'activities', keywords: ['bullseye', 'dart'] },

  // --- OBJECTS ---
  { emoji: '📱', category: 'objects', keywords: ['mobile phone', 'iphone'] },
  { emoji: '📲', category: 'objects', keywords: ['mobile phone with arrow'] },
  { emoji: '☎️', category: 'objects', keywords: ['telephone'] },
  { emoji: '📞', category: 'objects', keywords: ['telephone receiver'] },
  { emoji: '📟', category: 'objects', keywords: ['pager'] },
  { emoji: '📠', category: 'objects', keywords: ['fax machine'] },
  { emoji: '🔋', category: 'objects', keywords: ['battery'] },
  { emoji: '🔌', category: 'objects', keywords: ['electric plug'] },
  { emoji: '💻', category: 'objects', keywords: ['laptop computer'] },
  { emoji: '🖥️', category: 'objects', keywords: ['desktop computer'] },
  { emoji: '🖨️', category: 'objects', keywords: ['printer'] },
  { emoji: '⌨️', category: 'objects', keywords: ['keyboard'] },
  { emoji: '🖱️', category: 'objects', keywords: ['computer mouse'] },
  { emoji: '🖲️', category: 'objects', keywords: ['trackball'] },
  { emoji: '💽', category: 'objects', keywords: ['computer disk', 'minidisc'] },
  { emoji: '💾', category: 'objects', keywords: ['floppy disk', 'save'] },
  { emoji: '💿', category: 'objects', keywords: ['optical disk', 'cd'] },
  { emoji: '📀', category: 'objects', keywords: ['dvd'] },
  { emoji: '🧮', category: 'objects', keywords: ['abacus'] },
  { emoji: '📷', category: 'objects', keywords: ['camera', 'photo'] },
  { emoji: '📸', category: 'objects', keywords: ['camera with flash'] },
  { emoji: '📹', category: 'objects', keywords: ['video camera'] },
  { emoji: '🎥', category: 'objects', keywords: ['movie camera'] },
  { emoji: '📽️', category: 'objects', keywords: ['film projector'] },
  { emoji: '🎞️', category: 'objects', keywords: ['film frames'] },
  { emoji: '📞', category: 'objects', keywords: ['phone', 'call'] },
  { emoji: '📺', category: 'objects', keywords: ['television', 'tv'] },
  { emoji: '📻', category: 'objects', keywords: ['radio'] },
  { emoji: '🎙️', category: 'objects', keywords: ['studio microphone'] },
  { emoji: '🎚️', category: 'objects', keywords: ['level slider'] },
  { emoji: '🎛️', category: 'objects', keywords: ['control knobs'] },
  { emoji: '🧭', category: 'objects', keywords: ['compass', 'map'] },
  { emoji: '⏱️', category: 'objects', keywords: ['stopwatch'] },
  { emoji: '⏲️', category: 'objects', keywords: ['timer clock'] },
  { emoji: '⏰', category: 'objects', keywords: ['alarm clock'] },
  { emoji: '🕰️', category: 'objects', keywords: ['mantelpiece clock'] },
  { emoji: '⌛', category: 'objects', keywords: ['hourglass done'] },
  { emoji: '⏳', category: 'objects', keywords: ['hourglass not done'] },
  { emoji: '📡', category: 'objects', keywords: ['satellite antenna'] },
  { emoji: '🔋', category: 'objects', keywords: ['power', 'battery'] },
  { emoji: '🔌', category: 'objects', keywords: ['power', 'plug'] },
  { emoji: '💡', category: 'objects', keywords: ['light bulb', 'idea'] },
  { emoji: '🔦', category: 'objects', keywords: ['flashlight'] },
  { emoji: '🏮', category: 'objects', keywords: ['red paper lantern'] },
  { emoji: '🪔', category: 'objects', keywords: ['diya lamp'] },
  { emoji: '🕯️', category: 'objects', keywords: ['candle'] },
  { emoji: '🪔', category: 'objects', keywords: ['diya'] },
  { emoji: '🗑️', category: 'objects', keywords: ['trash can', 'bin'] },
  { emoji: '🛢️', category: 'objects', keywords: ['oil drum'] },
  { emoji: '💸', category: 'objects', keywords: ['money with wings'] },
  { emoji: '💵', category: 'objects', keywords: ['dollar banknote', 'money'] },
  { emoji: '💴', category: 'objects', keywords: ['yen banknote', 'money'] },
  { emoji: '💶', category: 'objects', keywords: ['euro banknote', 'money'] },
  { emoji: '💷', category: 'objects', keywords: ['pound banknote', 'money'] },
  { emoji: '💰', category: 'objects', keywords: ['money bag'] },
  { emoji: '💳', category: 'objects', keywords: ['credit card'] },
  { emoji: '💎', category: 'objects', keywords: ['gem stone', 'diamond'] },
  { emoji: '⚖️', category: 'objects', keywords: ['balance scale', 'justice'] },
  { emoji: '🧰', category: 'objects', keywords: ['toolbox'] },
  { emoji: '🔧', category: 'objects', keywords: ['wrench', 'tool'] },
  { emoji: '🔨', category: 'objects', keywords: ['hammer', 'tool'] },
  { emoji: '🛠️', category: 'objects', keywords: ['hammer and wrench'] },
  { emoji: '⛏️', category: 'objects', keywords: ['pick'] },
  { emoji: '⚙️', category: 'objects', keywords: ['gear', 'settings'] },
  { emoji: '🧱', category: 'objects', keywords: ['brick'] },
  { emoji: '⛓️', category: 'objects', keywords: ['chains'] },
  { emoji: '🪝', category: 'objects', keywords: ['hook'] },
  { emoji: '🧲', category: 'objects', keywords: ['magnet'] },
  { emoji: '🔫', category: 'objects', keywords: ['pistol', 'water gun'] },
  { emoji: '💣', category: 'objects', keywords: ['bomb'] },
  { emoji: '🧨', category: 'objects', keywords: ['firecracker'] },
  { emoji: '🔪', category: 'objects', keywords: ['kitchen knife', 'weapon'] },
  { emoji: '🗡️', category: 'objects', keywords: ['dagger'] },
  { emoji: '⚔️', category: 'objects', keywords: ['crossed swords'] },
  { emoji: '🛡️', category: 'objects', keywords: ['shield'] },
  { emoji: '🚬', category: 'objects', keywords: ['smoking', 'cigarette'] },
  { emoji: '⚰️', category: 'objects', keywords: ['coffin', 'dead'] },
  { emoji: '🪦', category: 'objects', keywords: ['headstone', 'dead'] },
  { emoji: '⚱️', category: 'objects', keywords: ['funeral urn'] },
  { emoji: '🏺', category: 'objects', keywords: ['amphora'] },
  { emoji: '🔮', category: 'objects', keywords: ['crystal ball', 'magic'] },
  { emoji: '🪄', category: 'objects', keywords: ['magic wand'] },
  { emoji: '📿', category: 'objects', keywords: ['prayer beads'] },
  { emoji: '🧿', category: 'objects', keywords: ['nazar amulet'] },
  { emoji: '💈', category: 'objects', keywords: ['barber pole'] },
  { emoji: '📡', category: 'objects', keywords: ['satellite'] },

  // --- SYMBOLS ---
  { emoji: '❤️', category: 'symbols', keywords: ['red heart', 'love'] },
  { emoji: '🧡', category: 'symbols', keywords: ['orange heart'] },
  { emoji: '💛', category: 'symbols', keywords: ['yellow heart'] },
  { emoji: '💚', category: 'symbols', keywords: ['green heart'] },
  { emoji: '💙', category: 'symbols', keywords: ['blue heart'] },
  { emoji: '💜', category: 'symbols', keywords: ['purple heart'] },
  { emoji: '🖤', category: 'symbols', keywords: ['black heart'] },
  { emoji: '🤍', category: 'symbols', keywords: ['white heart'] },
  { emoji: '🤎', category: 'symbols', keywords: ['brown heart'] },
  { emoji: '💔', category: 'symbols', keywords: ['broken heart'] },
  { emoji: '❣️', category: 'symbols', keywords: ['heart exclamation'] },
  { emoji: '💕', category: 'symbols', keywords: ['two hearts'] },
  { emoji: '💞', category: 'symbols', keywords: ['revolving hearts'] },
  { emoji: '💓', category: 'symbols', keywords: ['beating heart'] },
  { emoji: '💗', category: 'symbols', keywords: ['growing heart'] },
  { emoji: '💖', category: 'symbols', keywords: ['sparkling heart'] },
  { emoji: '💘', category: 'symbols', keywords: ['heart with arrow'] },
  { emoji: '💝', category: 'symbols', keywords: ['heart with ribbon'] },
  { emoji: '💟', category: 'symbols', keywords: ['heart decoration'] },
  { emoji: '☮️', category: 'symbols', keywords: ['peace symbol'] },
  { emoji: '✝️', category: 'symbols', keywords: ['latin cross'] },
  { emoji: '☪️', category: 'symbols', keywords: ['star and crescent'] },
  { emoji: '🕉️', category: 'symbols', keywords: ['om'] },
  { emoji: '☸️', category: 'symbols', keywords: ['wheel of dharma'] },
  { emoji: '✡️', category: 'symbols', keywords: ['star of david'] },
  { emoji: '🔯', category: 'symbols', keywords: ['six pointed star with dot'] },
  { emoji: '🕎', category: 'symbols', keywords: ['menorah'] },
  { emoji: '☯️', category: 'symbols', keywords: ['yin yang'] },
  { emoji: '☦️', category: 'symbols', keywords: ['orthodox cross'] },
  { emoji: '🛐', category: 'symbols', keywords: ['place of worship'] },
  { emoji: '⛎', category: 'symbols', keywords: ['ophiuchus'] },
  { emoji: '♈', category: 'symbols', keywords: ['aries'] },
  { emoji: '♉', category: 'symbols', keywords: ['taurus'] },
  { emoji: '♊', category: 'symbols', keywords: ['gemini'] },
  { emoji: '♋', category: 'symbols', keywords: ['cancer'] },
  { emoji: '♌', category: 'symbols', keywords: ['leo'] },
  { emoji: '♍', category: 'symbols', keywords: ['virgo'] },
  { emoji: '♎', category: 'symbols', keywords: ['libra'] },
  { emoji: '♏', category: 'symbols', keywords: ['scorpio'] },
  { emoji: '♐', category: 'symbols', keywords: ['射手座', 'sagittarius'] },
  { emoji: '♑', category: 'symbols', keywords: ['capricorn'] },
  { emoji: '♒', category: 'symbols', keywords: ['aquarius'] },
  { emoji: '♓', category: 'symbols', keywords: ['pisces'] },
  { emoji: '🆔', category: 'symbols', keywords: ['id'] },
  { emoji: '⚛️', category: 'symbols', keywords: ['atom symbol'] },
  { emoji: '🉑', category: 'symbols', keywords: ['japanese acceptable button'] },
  { emoji: '☢️', category: 'symbols', keywords: ['radioactive'] },
  { emoji: '☣️', category: 'symbols', keywords: ['biohazard'] },
  { emoji: '📴', category: 'symbols', keywords: ['mobile phone off'] },
  { emoji: '📳', category: 'symbols', keywords: ['vibration mode'] },
  { emoji: '🈶', category: 'symbols', keywords: ['japanese not free of charge button'] },
  { emoji: '🈚', category: 'symbols', keywords: ['japanese free of charge button'] },
  { emoji: '🈸', category: 'symbols', keywords: ['japanese application button'] },
  { emoji: '🈺', category: 'symbols', keywords: ['japanese open for business button'] },
  { emoji: '🈷️', category: 'symbols', keywords: ['japanese monthly amount button'] },
  { emoji: '✴️', category: 'symbols', keywords: ['eight pointed star'] },
  { emoji: '🆚', category: 'symbols', keywords: ['vs button'] },
  { emoji: '💮', category: 'symbols', keywords: ['white flower'] },
  { emoji: '🉐', category: 'symbols', keywords: ['japanese advantageous button'] },
  { emoji: '㊙️', category: 'symbols', keywords: ['japanese secret button'] },
  { emoji: '㊗️', category: 'symbols', keywords: ['japanese congratulations button'] },
  { emoji: '🈴', category: 'symbols', keywords: ['japanese passing grade button'] },
  { emoji: '🈵', category: 'symbols', keywords: ['japanese no vacancy button'] },
  { emoji: '🈹', category: 'symbols', keywords: ['japanese discount button'] },
  { emoji: '🈲', category: 'symbols', keywords: ['japanese prohibited button'] },
  { emoji: '🅰️', category: 'symbols', keywords: ['a button blood type'] },
  { emoji: '🅱️', category: 'symbols', keywords: ['b button blood type'] },
  { emoji: 'AB', category: 'symbols', keywords: ['ab button blood type'] },
  { emoji: '🆎', category: 'symbols', keywords: ['ab button'] },
  { emoji: '🅾️', category: 'symbols', keywords: ['o button blood type'] },
  { emoji: '🆘', category: 'symbols', keywords: ['sos button'] },
  { emoji: '❌', category: 'symbols', keywords: ['cross mark', 'no'] },
  { emoji: '⭕', category: 'symbols', keywords: ['heavy large circle'] },
  { emoji: '🛑', category: 'symbols', keywords: ['stop sign'] },
  { emoji: '⛔', category: 'symbols', keywords: ['no entry'] },
  { emoji: '📛', category: 'symbols', keywords: ['name badge'] },
  { emoji: '🚫', category: 'symbols', keywords: ['prohibited'] },
  { emoji: '💯', category: 'symbols', keywords: ['100'] },
  { emoji: '💢', category: 'symbols', keywords: ['anger'] },
  { emoji: '♨️', category: 'symbols', keywords: ['hot springs'] },
  { emoji: '🚷', category: 'symbols', keywords: ['no pedestrians'] },
  { emoji: '🚯', category: 'symbols', keywords: ['no littering'] },
  { emoji: '🚳', category: 'symbols', keywords: ['no bicycles'] },
  { emoji: '🚱', category: 'symbols', keywords: ['non-potable water'] },
  { emoji: '🔞', category: 'symbols', keywords: ['no one under eighteen'] },
  { emoji: '📵', category: 'symbols', keywords: ['no mobile phones'] },
  { emoji: '🚭', category: 'symbols', keywords: ['no smoking'] },
  { emoji: '❗', category: 'symbols', keywords: ['exclamation mark'] },
  { emoji: '❕', category: 'symbols', keywords: ['white exclamation mark'] },
  { emoji: '❓', category: 'symbols', keywords: ['question mark'] },
  { emoji: '❔', category: 'symbols', keywords: ['white question mark'] },
  { emoji: '‼️', category: 'symbols', keywords: ['double exclamation mark'] },
  { emoji: '⁉️', category: 'symbols', keywords: ['exclamation question mark'] },
  { emoji: '🔅', category: 'symbols', keywords: ['dim button'] },
  { emoji: '🔆', category: 'symbols', keywords: ['bright button'] },
  { emoji: '〽️', category: 'symbols', keywords: ['part alternation mark'] },
  { emoji: '⚠️', category: 'symbols', keywords: ['warning', 'danger'] },
  { emoji: '🚸', category: 'symbols', keywords: ['children crossing'] },
  { emoji: '🔱', category: 'symbols', keywords: ['trident emblem'] },
  { emoji: '⚜️', category: 'symbols', keywords: ['fleur-de-lis'] },
  { emoji: '🔰', category: 'symbols', keywords: ['japanese symbol for beginner'] },
  { emoji: '♻️', category: 'symbols', keywords: ['recycling symbol'] },
  { emoji: '✅', category: 'symbols', keywords: ['check mark button', 'ok'] },
  { emoji: '🈯', category: 'symbols', keywords: ['japanese reserved button'] },
  { emoji: '💹', category: 'symbols', keywords: ['chart increasing with yen'] },
  { emoji: '❇️', category: 'symbols', keywords: ['sparkle'] },
  { emoji: '✳️', category: 'symbols', keywords: ['eight-spoked asterisk'] },
  { emoji: '❎', category: 'symbols', keywords: ['cross mark button'] },
  { emoji: '🌐', category: 'symbols', keywords: ['globe with meridians'] },
  { emoji: '💠', category: 'symbols', keywords: ['diamond with a dot'] },
  { emoji: 'Ⓜ️', category: 'symbols', keywords: ['circled m'] },
  { emoji: '🌀', category: 'symbols', keywords: ['cyclone', 'twist'] },
  { emoji: '💤', category: 'symbols', keywords: ['zzz'] },
  { emoji: '🏧', category: 'symbols', keywords: ['atm sign'] },
  { emoji: '🚾', category: 'symbols', keywords: ['water closet', 'wc'] },
  { emoji: '♿', category: 'symbols', keywords: ['wheelchair symbol'] },
  { emoji: '🅿️', category: 'symbols', keywords: ['p button parking'] },
  { emoji: '🈳', category: 'symbols', keywords: ['japanese vacancy button'] },
  { emoji: '🈂️', category: 'symbols', keywords: ['japanese service charge button'] },
  { emoji: '🛂', category: 'symbols', keywords: ['passport control'] },
  { emoji: '🛃', category: 'symbols', keywords: ['customs'] },
  { emoji: '🛄', category: 'symbols', keywords: ['baggage claim'] },
  { emoji: '🛅', category: 'symbols', keywords: ['left luggage'] },
  { emoji: '🚹', category: 'symbols', keywords: ['men’s room'] },
  { emoji: '🚺', category: 'symbols', keywords: ['women’s room'] },
  { emoji: '🚼', category: 'symbols', keywords: ['baby symbol'] },
  { emoji: '⚧️', category: 'symbols', keywords: ['transgender symbol'] },
  { emoji: '🚻', category: 'symbols', keywords: ['restroom'] },
  { emoji: '🚮', category: 'symbols', keywords: ['litter in bin symbol'] },
  { emoji: '👣', category: 'symbols', keywords: ['footprints'] },
  { emoji: '🚻', category: 'symbols', keywords: ['toilet'] }
];
